### ISSUE TITLE
【建议】remove binary files

### ISSUE THREAD

**Issue by CookiePieWw** [TJ-CSCCG/TJCS-Course#62]
For historical reasons, many binary files remain in the repo, creating unnecessary complications for many operations. Also, it's necessary to give these files a home before moving on to #56.

Here are the possible steps to solve the problem:
- [x] Transfer valuable files to other storage services (Now they're on [OneDrive](https://1drv.ms/f/s!AsOZze73WaZ_gfczlR79TRrGQMUcbQ?e=uvJVVq))
- [x] Remove all the binary files in the repo
- [x] Reform the commit logs to reduce the size of .git

Since I'm not familiar with the binary files on both Git and GitHub, if you have any ideas or concerns about this, feel free to let me know, thanks! :-)

**Comment by CookiePieWw** [comment]
resolved by #63

**Comment by skyleaworlder** [comment]
It didn't work. The badge still shows 1.58GB instead of a smaller number.

I'm afraid I failed to handle this task correctly.

**Comment by CookiePieWw** [comment]
> It didn't work. The badge still shows 1.58GB instead of a smaller number.

The badge is more likely to be the problem. I cloned the repo and it shows a much smaller number:

![image](https://github.com/TJ-CSCCG/TJCS-Course/assets/59358312/4c69fc32-ae03-4d4e-ab57-68a722cf70a6)

[Here](https://github.com/orgs/community/discussions/23585) mentioned there may be some delay before our work shows its strength. Let's wait and see :-)

**Comment by skyleaworlder** [comment]
> > It didn't work. The badge still shows 1.58GB instead of a smaller number.
> 
> The badge is more likely to be the problem. I cloned the repo and it shows a much smaller number:
> 
> ![image](https://private-user-images.githubusercontent.com/59358312/286559877-4c69fc32-ae03-4d4e-ab57-68a722cf70a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTQ5ODMsIm5iZiI6MTcwMTI1NDY4MywicGF0aCI6Ii81OTM1ODMxMi8yODY1NTk4NzctNGM2OWZjMzItYWUwMy00ZDRlLWFiNTctNjhhNzIyY2Y3MGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEwNDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NGQzMmUwN2IyMzA1MjlkZWY5MjhlNjhkMDQyMjViZDYzOWI0N2U1ZDEzNTIyZDI3NDBlMjIyZjA5ZmE0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e8Yvwpfl0fPwaaZyiK6nk3aqN3ayRL5CPHehLEbXSg8)
> 
> [Here](https://github.com/orgs/community/discussions/23585) mentioned there may be some delay before our work shows its strength. Let's wait and see :-)

OK. Actually, the badge is not our goal. That's all right as long as the repository indeed become smaller,

**Comment by skyleaworlder** [comment]
![image](https://github.com/TJ-CSCCG/TJCS-Course/assets/45269589/46324092-4e67-4c92-be0f-1ab2a246b396)

Currently, the repo size has been significantly reduced! Thanks for your contribution!
